### ISSUE TITLE
Unsure what this means, any help?

### ISSUE THREAD

**Issue by alexanderosmith** [danijoo/sync_zotero_remarkable#8]
I attempted to set this up using pcloud and when I ran it this is what the output was. I'm assuming this means it recognizes there are two pdfs to sync, but I'm not familiar with this code enough to trace back what the issue is. Any ideas?

user@ubuntuComputer:~/sync_zotero_remarkable$ sync_zotero_rm
Fetching collection from Zotero... Done.
Fetching item list... Done.
Items to sync: 2
Traceback (most recent call last):
  File "/home/aos11409/.local/bin/sync_zotero_rm", line 70, in <module>
    rm_items = rmapy.get_meta_items()
  File "/home/aos11409/.local/lib/python3.8/site-packages/rmapy/api.py", line 180, in get_meta_items
    for item in response.json():
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dnlbauer** [comment]
Hi, seems like the problem is not on the side of zotero/your cloud, but from rmapy.
Since `rmapy` uses the same credentials als storage files `rmapi` is using, can you please confirm that you can access the device from command line with the `rmapi` command line interface ([rmapi](https://github.com/juruen/rmapi))?
If this works (or once you regenerated your api keys with rmapi), my script should also work.

I havent put a lot of work into the part that generates api keys etc, so this is the fix that usually works for me when rmapy fails to connect to the remarkable cloud. Let me know if this helps
