### ISSUE TITLE
Error Syncing Files

### ISSUE THREAD

**Issue by funkeyfreak** [danijoo/sync_zotero_remarkable#9]
When running the application for the first time, I run into the following exception:

> Fetching collection from Zotero... Done.
> Fetching item list... Done.
> Items to sync: 2
> Traceback (most recent call last):
>   File "/usr/local/anaconda3/bin/sync_zotero_rm", line 70, in <module>
>     rm_items = rmapy.get_meta_items()
>   File "/usr/local/anaconda3/lib/python3.8/site-packages/rmapy/api.py", line 180, in get_meta_items
>     for item in response.json():
>   File "/usr/local/anaconda3/lib/python3.8/site-packages/requests/models.py", line 897, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 

I am able to run `rmapi` standalone - I am wondering if you could help?

**Comment by opal06** [comment]
This seems to be a duplicaten this issue:https://github.com/danijoo/sync_zotero_remarkable/issues/7

Maybe that can help you...
